<script setup lang="ts">
const i18nHead = useLocaleHead()

// Apple splash screens generated by `pnpm --filter @template/web pwa-assets`
// (pwa-assets.config.ts): black #000000, contain, padding 0.3 from public/icon.svg.
// iOS ignores the web manifest splash — these links are the Apple equivalent.
const appleSplashLinks = [
  { media: 'screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', href: '/nuxt-template/apple-splash-portrait-light-1170x2532.png' },
  { media: 'screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', href: '/nuxt-template/apple-splash-landscape-light-2532x1170.png' },
  { media: 'screen and (prefers-color-scheme: dark) and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', href: '/nuxt-template/apple-splash-portrait-dark-1170x2532.png' },
  { media: 'screen and (prefers-color-scheme: dark) and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', href: '/nuxt-template/apple-splash-landscape-dark-2532x1170.png' },
  { media: 'screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', href: '/nuxt-template/apple-splash-portrait-light-1206x2622.png' },
  { media: 'screen and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', href: '/nuxt-template/apple-splash-landscape-light-2622x1206.png' },
  { media: 'screen and (prefers-color-scheme: dark) and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)', href: '/nuxt-template/apple-splash-portrait-dark-1206x2622.png' },
  { media: 'screen and (prefers-color-scheme: dark) and (device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)', href: '/nuxt-template/apple-splash-landscape-dark-2622x1206.png' },
  { media: 'screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', href: '/nuxt-template/apple-splash-portrait-light-1640x2360.png' },
  { media: 'screen and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', href: '/nuxt-template/apple-splash-landscape-light-2360x1640.png' },
  { media: 'screen and (prefers-color-scheme: dark) and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)', href: '/nuxt-template/apple-splash-portrait-dark-1640x2360.png' },
  { media: 'screen and (prefers-color-scheme: dark) and (device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)', href: '/nuxt-template/apple-splash-landscape-dark-2360x1640.png' },
]

useHead(() => ({
  htmlAttrs: { lang: i18nHead.value.htmlAttrs?.lang ?? 'en' },
  meta: [
    { id: 'theme-color', name: 'theme-color', content: '#000000' },
    { name: 'mobile-web-app-capable', content: 'yes' },
    { name: 'apple-mobile-web-app-capable', content: 'yes' },
    { name: 'apple-mobile-web-app-status-bar-style', content: 'black' },
    { name: 'apple-mobile-web-app-title', content: 'Template' },
  ],
  link: [
    { rel: 'apple-touch-icon', href: '/nuxt-template/apple-touch-icon-180x180.png' },
    ...appleSplashLinks.map(l => ({ rel: 'apple-touch-startup-image', media: l.media, href: l.href })),
  ],
}))
</script>

<template>
  <NuxtLoadingIndicator />
  <NuxtPwaManifest />
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
